# Generated by Django 6.0 on 2025-12-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(default='3 days', help_text="Expected delivery time (e.g., '2 days', '1 week')", max_length=100),
            preserve_default=False,
        ),
    ]
