# Generated by Django 6.0.4 on 2026-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_wallet_balance_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_file',
            field=models.FileField(blank=True, help_text='The final completed work uploaded by the freelancer', null=True, upload_to='deliveries/'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes from the freelancer upon delivery'),
        ),
    ]
