# Generated by Django 6.0.4 on 2026-04-27 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_delivery_file_order_delivery_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='A short bio displayed on the public profile page'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile avatar shown across the platform', null=True, upload_to='profile_pictures/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Star rating from 1 (poor) to 5 (excellent)')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional written feedback from the buyer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='The completed order this review is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.order')),
                ('reviewee', models.ForeignKey(help_text='The freelancer being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='The buyer who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
