# Generated by Django 6.0.4 on 2026-05-09 17:44

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_otp'),
    ]

    operations = [
        VectorExtension(),
    ]
