# Generated by Django 6.0.4 on 2026-05-09 17:49

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
